MQTT_CLIENT_KEY = "mqtt client key"
MQTT_CLIENT_CERT = "mqtt client cert"
MQTT_BROKER = "mqtt broker"
MQTT_BROKER_CA = "mqtt broker ca"
MQTT_TOPIC = "pico"
TWILIO_ACCOUNT_SID = "twilio account sid" 
TWILIO_AUTH_TOKEN = "twilio auth token" 
TWILIO_SENDER_NUM = "twilio sender num" 
